version: '3.8'
services:
  main_app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    env_file:
      - ./.env
    entrypoint:
      - ./entrypoint.sh
    depends_on:
      - db

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    depends_on:
      - main_app
      - db
    volumes:
      - ./static/:/static
    env_file:
      - ./.env
    ports:
      - 80:80

  db:
    image: postgres:13.0-alpine
    restart: always
    volumes:
      - pgdata_for_main_app/:/var/lib/postgresql/data
    env_file:
      - ./.env
    expose:
      - 5432

volumes:
    pgdata_for_main_app:
      external: true
